name:
  Sitetracker Cron Workflow
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - uses: actions/checkout@v3
        with:
          working-directory: /home/runner/work/sitetracker/sitetracker/cron
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          working-directory: /home/runner/work/sitetracker/sitetracker/cron
      - run: npm install
        working-directory: /home/runner/work/sitetracker/sitetracker/cron
      - name: Run script
        run: npm start
        working-directory: /home/runner/work/sitetracker/sitetracker/cron
