name:
  Sitetracker Cron Workflow
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cron
    steps:
      # Runs a single command using the runners shell
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - run: npm install
      - name: Run script
        run: npm start